import Header from '../../components/Header';
import Footer from '../../components/Footer';
import '../../css/StaticPages.css';

export default function HistoryPage() {
  return (
    <div className="static-page">
      <Header />
      <main className="static-main">
        <section className="static-hero">
          <h1>Povijest Studentskog centra</h1>
          <p>Prošlost, sadašnjost i budućnost Studentskog centra u Zagrebu</p>
        </section>
        <section className="static-content">
          <article>
            <h2>Korijeni i razvoj</h2>
            <p>{`Prošlost, sadašnjost, a i budućnost Studentskoga centra u Zagrebu (dalje: SC), stožerne ustanove studentskoga standarda, pa i socijalne sigurnosti studenata, neraskidivo je vezana za sveučilišni život u Zagrebu. Ali, ne samo u Zagrebu. Zagreb jest “rodno” i radno mjesto SC-a, ali je njegovo djelovanje mnogo širih okvira i dometa. Naime, SC je ustrojbena jedinica Sveučilišta u Zagrebu koje je svojim djelovanjem zadovoljavalo intelektualne, znanstvene, kulturne, duhovne i društvene potrebe ne samo Zagreba i Hrvatske, nego i širega područja.`}</p>
            <p>{`Studentski centar Sveučilišta u Zagrebu, sveučilišna ustanova od posebnoga društvenog interesa i značenja, ustanova je s vrlo razgranatom i kompleksnom djelatnosti na području izvannastavnoga života i standarda studenata.`}</p>
            <p>{`Široka djelatnost zacrtana je još u osnivačkom aktu od 1. lipnja 1957.godine. Studenti su dobili prostor bivšega Zagrebačkog velesajma za potrebe SC-a u Savskoj 25. On će postati središnjim, najfrekventnijim i najstudentskijim mjestom studentskih zbivanja na Sveučilištu, u gradu i u Hrvatskoj. Odnosno, zašto ne reći “svetim” prostorom brojnih generacija hrvatskih sveučilištaraca.`}</p>
            <p>{`Adaptacije dobivenih prostora za potrebe SC-a u Savskoj 25 započete su potkraj 1958. a završene su uglavnom potkraj 1962. godine. U adaptirane i dograđene prostore za studentske prehrambene potrebe, potrebe studentskoga rada, kulturnog, obrazovnog i zabavnoga sadržaja ušli su studenti i servisi za studentske usluge.`}</p>
            <p>{`Svečano otvaranje SC-a 15. travnja 1959. (restoran, kino,...) bila je velika pobjeda studenata, a potom je sve išlo lakše: Klub SC, učionica, Galerija SC, Komorna pozornica (Teatar &TD) stvorit će od SC-a kultno mjesto ne samo studentskih, nego i širih društvenih sadržaja i značenja. Osposobljavanjem restorana, odnosno kuhinjskog i konzumnoga prostora u SC u travnju 1959., počinje pružanje usluga prehrane studenata i to kao dodatni i prošireni zadatak utemeljiteljskom aktu SC-a.`}</p>
            <p>{`Šest godina poslije (1965.), kao zadatak SC-a postao je i briga za smještaj studenata. Tako je i druga aktivnost egzistencijalne naravi studenata postala društvenim zadatkom SC-a, a SC postao pravom socijalnom ustanovom. Međutim, broj studenata Sveučilišta u Zagrebu, poglavito nedomicilnih, stalno je rastao tako da je smještaj studenata od početka gorući problem, kako SC-a, tako i studenata, a i zajednice u cjelini. Iako su zajednica i SC mnogo pokušavali i radili na rješavanju toga problema, mora se priznati da broj ležaja od 1957. (1400) do 2011. (oko 7500) za tih pedesetak godina nije dostatno povećan. Istina, mora se priznati da su u međuvremenu neki domovi (“Dubrava”, “Tvrtkova”, “SD Ivan Meštrović”) prestali funkcionirati, da je mnogo urađeno na poboljšanju kakvoće stanovanja, da se smještaj subvencionira i da studenti stanari domova danas za relativno mali iznos imaju udoban smještaj s bogatim sadržajem u domu. Osim toga, danas se subvencionira i tri tisuće studenata u privatnom smještaju.`}</p>
            <p>{`Konzumni prostor u SC-u, domovima i fakultetima (danas na 12 lokacija –uglavnom restorana, s raznovrsnim modelima ponude) s prosječno od oko dvadesetšest tisuća dnevno proizvedenih obroka ili preko osam milijuna obroka posljednjih godina, dokaz su da je SC načelom “ići za studentom” uvelike razgranao svoju konzumnu mrežu. Suvremeni način ponude i višestruki izbor načina prehrane također dokazuju da SC čini sve u korist studenta, njegova standarda, statusa i zadovoljstva. Visoko dostignuta razina usluga prehrane potvrđuje se i kroz maksimalnu primjenu veterinarskih, higijenskih i sanitarnih kriterija.`}</p>
            <p>{`U SC-u djeluje i Student servis (osnovan 1957. kao Biro za zapošljavanje studenata), najstarija poslovna jedinica u SC-u. Zahvaljujući postojanju i djelovanju servisa, podizan je osobni i društveni standard studenata. Treba li reći da je brojnim studentima, kasnijim intelektualcima, bio jedini, glavni ili pak dopunski izvor egzistiranja? Ne samo to! Zarađena sredstva Servisa ulagana su u projekte, objekte i sredstva potrebna za nužno ili bolje pružanje usluga studentima, tj. investicije i investicijsko održavanje, za financiranje društvenih, kulturnih, športskih, humanih potreba itd.`}</p>
            <p>{`Iz navedenoga proizlazi da je SC s vremenom rastao, razvijao se, kompletirao i gradio puteve do i za studenta, a time ispunjavao društvenu obvezu. Dograđivao se poslovno, organizacijski, kadrovski i stručno, povećavao opseg poslovanja i ponuda te kvalitetu usluga.`}</p>
            <p>{`Ne zaboravimo: SC nije odrađivao samo skrb za studentski standard, nego i dodatne društvene obveze i zadatke, poglavito u posebnim i izvanrednim prilikama (npr. poplava Zagreba 1964., Univerzijada `+"`87."+`, 2. Svjetske vojne igre 1999. i dr.). I u doba Domovinskoga rata SC je maksimalno bio na raspolaganju domovini Hrvatskoj i njezinim građanima, osobito braniteljima i ratnim stradalnicima i dao maksimalni prilog svomu narodu.`}</p>
            <p>{`Studentski centar nadilazi egzistencijalnu studentsku stvarnost. Studentski domovi, pa i restorani, mjesta su njihova svakidašnjeg življenja, zamjena za roditeljski dom i obitelj, tu se odrasta i sazrijeva. Tu se događa i prva, i prava ljubav, i vjenčanja, pripravlja za stvarni život i profesionalni rad.`}</p>
            <p>{`SC kao sveučilišna sastavnica nije mjesto događanja svakodnevne i profesionalne politike. Ipak statusom sveučilišne autonomije te svojim kapacitetima, prostorima i potencijalima omogućio je mladima i taj oblik rada. SC je mjesto rađanja novih političkih, nacionalnih, domoljubnih ideja, buntova i sličnih događanja. Tu se gajila, njegovala i razvijala demokracija i domoljublje, te je SC time sebi osigurao istaknuto mjesto u novijoj hrvatskoj političkoj povijesti. S pravom i s ponosom se može reći da je SC, kao dio odgojno-obrazovnoga sustava, unatoč svim pogreškama i slabostima u poslovanju, u prošlih pedesetak godina uspješno odradio domovinski i nacionalni zadatak a danas uspješno i na moderan način nudi i odrađuje uglavnom zaokruženu ponudu studentskih usluga. SC je bio matica i košnica mladih sveučilištaraca, ali i drugih vezanih uz rad Sveučilišta. Ne samo da je SC ostvario zadatke utemeljiteljskog akta iz 1957., nego je prateći duh vremena, nove ideje, medije i tehnologije studentima kontinuirano pružao uslugu više, nove usluge, da bi mladi intelektualac na polju ovladavanja znanjima i tehnologijama mogao uspješno odgovoriti osobnoj, nacionalnoj i domovinskoj obvezi.`}</p>
            <p>{`SC je i dalje okosnica studentskoga standarda, putokaz i mjerilo ostalim sličnim centrima u državi. Smješten je na potezu Sveučilišne aleje: Sveučilište (Rektorat) – Fakultet strojarstva i brodogradnje, pa je i u fizičkom, ali i simboličkom smislu sveučilišna poveznica, poglavito kako je 2007. otvoren istočni ulaz pa je SC postao još frekventnijim. Istina, SC prostor potrebno je još dograditi, oblikovati, oplemeniti i revitalizirati sveučilišnim i drugim sadržajima. Otvara se niz kreativnih i korisnih mogućnosti i sadržaja multifunkcionalnog i multikompleksnoga karaktera.`}</p>
            <h2>SC kultura</h2>
            <p>{`SC je od svojih početaka kreator i organizator kulturne djelatnosti i bio permanentno, kontinuirano i odgovorno na usluzi studentima. Ponuda se sastojala od sadržaja i oblika kulturnog, umjetničkog, zabavnog, obrazovnog, informativnog i duhovnoga karaktera. Kazališna, likovna, glazbena, filmska umjetnost, multimediji, nakladništvo, razni informativni mediji i sadržaji, duhovni sadržaji itd. u lepezi su ponude studentima, zagrebačkoj mladeži, a i građanstvu.`}</p>
            <p>{`SC je u zasigurno bio najproduktivnija kuća kulturnih sadržaja u Hrvatskoj. Radi se o kulturnom centru, centru multikulturnih i interaktivnih aktivnosti i značaja s kakvim se ni u europskim okvirima ne susreće često. Alternativa, konceptualna, novovalna... umjetnost ovdje se porodiše i nađoše svoj dom. Stoga je SC u životu glavnoga grada, nekada republike, a danas hrvatske države, sebi osigurao visoko, možda i vodeće mjesto kao tvorac i organizator kulturnih sadržaja.`}</p>
            <p>{`Kako je kulturno i umjetničko izražavnje u SC-u odavno zaživjelo, neprekinuto i redovito se održava, time je postignuta i institucionalizacija kulturnog i umjetničkog izražavanja. Stvorene su ustanove od kojih su neke odavno priznate i izvan Republike Hrvatske. Riječ je o Teatru &TD, Galeriji SC, Kinu SC, Muzičkom salonu, MM centru, SKUC-u itd. Zar bismo mogli preskočiti tribinu "5 minuta poslije 8", časopise "Razlog", "Teku", Gordogan, Novine Galerije SC itd. Z-3 i Radio 101., nacionalne manifestacije Dani hrvatskog filma i Pasionska baština, suvremeni projekti Kulture promjene svoje rodno mjesto imaju u SC-u. Neke od navedenih jedinica postale su, već davno, prepoznatljivim ne samo u nacionalnim okvirima.`}</p>
            <p>{`Mora se istaknuti oporbeni, alternativni i nekonvencionalni značaj u SC kulture kroz cijelo razdoblje njegova postojanja. Kao pokretač urbane kulture ne samo studenata nego i čitave alternativne scene Zagreba i Hrvatske (npr. Razlog, Teka, studentska tribina, Festival animiranih filmova, Muzički biennale, konceptualna umjetnost, novovalna scena, kazališne radionice, Omladinski/Radio 101, OTV, suradnja sa Studentskim listom, Poletom te u ostalim poljima djelovanja) simbolizirala je otpor mladih ne samo kulturnom, nego i političkom dogmatizmu, monolitizmu i jednoumlju. Pored Katoličke crkve, ovo je bilo središnje mjesto, glavno svjetovno središte duhovnog, intelektualnog, kulturnog i političkog otpora, a povremeno i bunta, sveprisutnom i svevladajućem dogmatizmu, unitarizmu i totalitarizmu u društvu.`}</p>
            <p>{`Bitna obilježja kulture, odnosno ukupne kulturne djelatnosti SC-a su: suvremenost, liberalizacija i institucionalizacija kulture u okviru SC-a, otvorenost, upitnost, interdisciplinarnost, hrabrost, laboratorij, novum, instalacija novoga, alternativa, granična problematika, profesionalni, paraprofesionalni i amaterski rad.`}</p>
            <p>{`SC je pri realizaciji programa, projekata i ukupne aktivnosti ostvario bogatu i raznovrsnu suradnju sa Sveučilištem u Zagrebu, Studentskim centrima u zemlji i inozemstvu, gradom Zagrebom, državnim ustanovama, gospodarskim subjektima, pojedinim inozemnim ustanovama. Ostvarena je suradnja s brojnim ustanovama u gradu, u Hrvatskoj, na prostoru bivše države. K tomu, i u inozemstvu, na europskoj, pa i svjetskoj sceni, ali i razini. Stoga su rezultati na polju kulture i umjetnosti, unatoč uvijek aktualnoj besparici golemi, te je u tom smislu dao znatan prinos Sveučilištu, gradu Zagrebu, Republici Hrvatskoj i naciji. Poglavito to vrijedi za Teatar &TD, Galeriju SC, MMC. Nećemo pretjerati ako kažemo da su, unatoč propustima, promašajima i nedostatcima, njegovi brojni rezultati internacionalnoga značaja i značenja. Zbog ukupnog prinosa SC-a, poglavito na polju kulture te zbog Zagrebačkog zbora/velesajma koji je bio novum za to vrijeme, adresu Savsku 25 dobri poznavatelji ovoga prostora nazivaju „arheologijom modernosti“. `}</p>
            <p>{`Ima li SC kultura svoj identitet? Da, ima! Ona je svakako prepoznatljiva, studentska i istraživačka, što je zajednički nazivnik ukupne kulturne ponude i realizacije. Međutim, SC kulturu obilježavaju raspršeni, višestruki, policentrični identiteti s obzirom na različite umjetnosti i iz njih proistekle, i već davno afirmirane ustanove (Teatar &TD, GSC, MMC…).`}</p>
            <p>{`SC je istovremeno i živi spomenik, ali i suvremena radionica i laboratorij studentskoga standarda u Hrvatskoj. Zasigurno, na korist i ponos hrvatskom društvu.`}</p>
          </article>
        </section>
      </main>
      <Footer />
    </div>
  );
}
